import type { UtilityToolCategory, UtilityToolDefinition } from "@/types/utility-tools";

export const UTILITY_TOOL_CATEGORIES: {
  id: UtilityToolCategory;
  label: string;
  icon: string;
  description: string;
}[] = [
  {
    id: "seo-meta",
    label: "SEO & Meta Tags",
    icon: "🔍",
    description: "Generate meta titles, descriptions, Open Graph tags, robots.txt, and more for better search visibility.",
  },
  {
    id: "schema-markup",
    label: "Schema Markup",
    icon: "📐",
    description: "Create structured data markup for rich snippets in Google search results.",
  },
  {
    id: "text-content",
    label: "Text & Content",
    icon: "📝",
    description: "Analyze, transform, and generate text content for websites and marketing.",
  },
  {
    id: "business-tools",
    label: "Business Tools",
    icon: "💼",
    description: "Generate business documents, policies, invoices, and branding assets.",
  },
  {
    id: "link-generators",
    label: "Link Generators",
    icon: "🔗",
    description: "Create review links, UTM URLs, QR codes, and embeddable map widgets.",
  },
  {
    id: "image-tools",
    label: "Image Tools",
    icon: "🖼️",
    description: "Compress, resize, crop, and convert images between formats in your browser.",
  },
  {
    id: "dev-utilities",
    label: "Dev Utilities",
    icon: "🛠️",
    description: "Minify code, generate hashes, encode data, and convert colors and timestamps.",
  },
  {
    id: "calculators",
    label: "Calculators",
    icon: "🧮",
    description: "Calculate percentages, margins, discounts, and taxes for everyday business needs.",
  },
];

export const UTILITY_TOOLS: UtilityToolDefinition[] = [
  // ---------------------------------------------------------------------------
  // SEO Meta (9 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "meta-title-generator",
    name: "Meta Title Generator",
    description: "Generate SEO-optimized meta titles for your web pages. Create compelling title tags that improve click-through rates in search results.",
    icon: "🏷️",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["meta title", "title tag", "seo title", "page title"],
  },
  {
    slug: "meta-description-generator",
    name: "Meta Description Generator",
    description: "Create persuasive meta descriptions that drive clicks from search engine results pages. Stay within the recommended character limits.",
    icon: "📋",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["meta description", "seo description", "serp snippet", "search description"],
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate a complete set of HTML meta tags for your web pages including viewport, charset, author, and SEO-related tags.",
    icon: "🔖",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["meta tags", "html meta", "head tags", "seo tags"],
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Create a properly formatted robots.txt file to control how search engine crawlers access and index your website.",
    icon: "🤖",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["robots txt", "crawl control", "search engine crawl", "bot directives"],
  },
  {
    slug: "xml-sitemap-generator",
    name: "XML Sitemap Generator",
    description: "Generate a valid XML sitemap to help search engines discover and index all the important pages on your website.",
    icon: "🗺️",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["xml sitemap", "sitemap generator", "search index", "site map"],
  },
  {
    slug: "canonical-tag-generator",
    name: "Canonical Tag Generator",
    description: "Generate canonical link tags to prevent duplicate content issues and consolidate ranking signals to your preferred URL.",
    icon: "🔗",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["canonical tag", "duplicate content", "canonical url", "rel canonical"],
  },
  {
    slug: "open-graph-generator",
    name: "Open Graph Tag Generator",
    description: "Create Open Graph meta tags so your pages look great when shared on Facebook, LinkedIn, and other social platforms.",
    icon: "📣",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["open graph", "og tags", "social sharing", "facebook meta"],
  },
  {
    slug: "twitter-card-generator",
    name: "Twitter Card Generator",
    description: "Generate Twitter Card meta tags to control how your content appears when shared on Twitter/X with rich media previews.",
    icon: "🐦",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["twitter card", "twitter meta", "x card", "social preview"],
  },
  {
    slug: "hreflang-tag-generator",
    name: "Hreflang Tag Generator",
    description: "Generate hreflang tags for multilingual and multi-regional websites to help search engines serve the correct language version.",
    icon: "🌐",
    category: "seo-meta",
    toolType: "generator",
    keywords: ["hreflang", "multilingual seo", "international seo", "language tags"],
  },

  // ---------------------------------------------------------------------------
  // Schema Markup (15 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "local-business-schema-generator",
    name: "Local Business Schema Generator",
    description: "Generate JSON-LD structured data for local businesses to appear in Google Maps and local search results with rich info.",
    icon: "🏪",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["local business schema", "json-ld", "local seo", "google maps schema"],
  },
  {
    slug: "organization-schema-generator",
    name: "Organization Schema Generator",
    description: "Create Organization structured data markup so Google displays your company name, logo, and contact details in search results.",
    icon: "🏢",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["organization schema", "company schema", "brand markup", "json-ld"],
  },
  {
    slug: "website-schema-generator",
    name: "Website Schema Generator",
    description: "Generate WebSite schema markup to enable sitelinks search boxes and help search engines understand your site structure.",
    icon: "🌍",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["website schema", "sitelinks", "search box schema", "json-ld"],
  },
  {
    slug: "person-schema-generator",
    name: "Person Schema Generator",
    description: "Create Person structured data for authors, founders, or team members to build knowledge panel presence in search results.",
    icon: "👤",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["person schema", "author schema", "knowledge panel", "json-ld"],
  },
  {
    slug: "article-schema-generator",
    name: "Article Schema Generator",
    description: "Generate Article or BlogPosting schema markup to enhance how your blog posts and news articles appear in Google Search.",
    icon: "📰",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["article schema", "blog schema", "news schema", "json-ld"],
  },
  {
    slug: "faq-schema-generator",
    name: "FAQ Schema Generator",
    description: "Create FAQPage structured data to display expandable question-and-answer rich results directly in Google search.",
    icon: "❓",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["faq schema", "question answer", "rich results", "json-ld"],
  },
  {
    slug: "breadcrumb-schema-generator",
    name: "Breadcrumb Schema Generator",
    description: "Generate BreadcrumbList schema markup to show a breadcrumb trail in search results, improving navigation visibility.",
    icon: "🍞",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["breadcrumb schema", "navigation markup", "breadcrumb trail", "json-ld"],
  },
  {
    slug: "product-schema-generator",
    name: "Product Schema Generator",
    description: "Create Product structured data with price, availability, and review info for rich product listings in Google Shopping.",
    icon: "🛍️",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["product schema", "shopping markup", "price schema", "json-ld"],
  },
  {
    slug: "review-schema-generator",
    name: "Review Schema Generator",
    description: "Generate Review and AggregateRating schema to display star ratings in search results and boost click-through rates.",
    icon: "⭐",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["review schema", "star rating", "aggregate rating", "json-ld"],
  },
  {
    slug: "event-schema-generator",
    name: "Event Schema Generator",
    description: "Create Event structured data so your upcoming events appear in Google Search with date, venue, and ticket details.",
    icon: "📅",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["event schema", "event markup", "calendar schema", "json-ld"],
  },
  {
    slug: "recipe-schema-generator",
    name: "Recipe Schema Generator",
    description: "Generate Recipe schema markup to display cooking time, ingredients, and ratings as rich results in Google Search.",
    icon: "🍳",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["recipe schema", "cooking markup", "food schema", "json-ld"],
  },
  {
    slug: "video-schema-generator",
    name: "Video Schema Generator",
    description: "Create VideoObject structured data so your videos appear with thumbnails and duration info in Google search results.",
    icon: "🎬",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["video schema", "video markup", "youtube schema", "json-ld"],
  },
  {
    slug: "job-posting-schema-generator",
    name: "Job Posting Schema Generator",
    description: "Generate JobPosting schema to list your open positions in Google for Jobs with salary, location, and requirements.",
    icon: "💼",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["job posting schema", "job listing", "hiring markup", "json-ld"],
  },
  {
    slug: "howto-schema-generator",
    name: "HowTo Schema Generator",
    description: "Create HowTo structured data to display step-by-step instructions as rich results in Google search.",
    icon: "📖",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["howto schema", "tutorial markup", "step by step", "json-ld"],
  },
  {
    slug: "service-schema-generator",
    name: "Service Schema Generator",
    description: "Generate Service schema markup to highlight your business services with descriptions and pricing in search results.",
    icon: "🔧",
    category: "schema-markup",
    toolType: "generator",
    keywords: ["service schema", "service markup", "business service", "json-ld"],
  },

  // ---------------------------------------------------------------------------
  // Text & Content (17 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "keyword-density-checker",
    name: "Keyword Density Checker",
    description: "Analyze keyword frequency and density in your content. Identify over-optimized or under-used keywords for better on-page SEO.",
    icon: "🔑",
    category: "text-content",
    toolType: "counter",
    keywords: ["keyword density", "keyword frequency", "seo analysis", "content optimization"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs in your text instantly. Track content length for SEO and editorial guidelines.",
    icon: "🔢",
    category: "text-content",
    toolType: "counter",
    keywords: ["word count", "character count", "text length", "content counter"],
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    description: "Count characters with and without spaces in your text. Perfect for staying within social media and meta tag character limits.",
    icon: "🔤",
    category: "text-content",
    toolType: "counter",
    keywords: ["character count", "letter count", "text length", "char counter"],
  },
  {
    slug: "reading-time-calculator",
    name: "Reading Time Calculator",
    description: "Estimate how long it takes to read your content based on average reading speed. Useful for blog posts and article planning.",
    icon: "⏱️",
    category: "text-content",
    toolType: "counter",
    keywords: ["reading time", "read time", "content length", "article duration"],
  },
  {
    slug: "readability-checker",
    name: "Readability Checker",
    description: "Analyze the readability of your text using Flesch-Kincaid and other scoring methods. Ensure your content is accessible to your audience.",
    icon: "📊",
    category: "text-content",
    toolType: "counter",
    keywords: ["readability score", "flesch kincaid", "content readability", "reading level"],
  },
  {
    slug: "url-slug-generator",
    name: "URL Slug Generator",
    description: "Convert any text into clean, SEO-friendly URL slugs. Automatically handles special characters, spaces, and accented letters.",
    icon: "🔗",
    category: "text-content",
    toolType: "text-transform",
    keywords: ["url slug", "permalink", "seo url", "url formatter"],
  },
  {
    slug: "serp-snippet-preview",
    name: "SERP Snippet Preview",
    description: "Preview how your page will look in Google search results. Visualize your title, URL, and meta description before publishing.",
    icon: "👁️",
    category: "text-content",
    toolType: "generator",
    keywords: ["serp preview", "google preview", "search result preview", "snippet preview"],
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    description: "Quickly remove duplicate lines from your text while preserving the original order. Great for cleaning up keyword lists and data.",
    icon: "🧹",
    category: "text-content",
    toolType: "text-transform",
    keywords: ["remove duplicates", "deduplicate", "unique lines", "clean text"],
  },
  {
    slug: "remove-extra-spaces",
    name: "Remove Extra Spaces",
    description: "Strip extra whitespace, tabs, and unnecessary blank lines from your text. Clean up copied content in one click.",
    icon: "✂️",
    category: "text-content",
    toolType: "text-transform",
    keywords: ["remove spaces", "trim whitespace", "clean text", "strip spaces"],
  },
  {
    slug: "text-sorter",
    name: "Text Sorter",
    description: "Sort lines of text alphabetically, numerically, or in reverse order. Organize lists, keywords, and data effortlessly.",
    icon: "🔀",
    category: "text-content",
    toolType: "text-transform",
    keywords: ["sort text", "alphabetical sort", "sort lines", "order text"],
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse your text character by character or line by line. Useful for encoding, puzzles, and creative text effects.",
    icon: "🔄",
    category: "text-content",
    toolType: "text-transform",
    keywords: ["reverse text", "backwards text", "mirror text", "flip text"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between uppercase, lowercase, title case, sentence case, and camelCase formats instantly.",
    icon: "🔠",
    category: "text-content",
    toolType: "text-transform",
    keywords: ["case converter", "uppercase", "lowercase", "title case", "camelcase"],
  },
  {
    slug: "line-counter",
    name: "Line Counter",
    description: "Count the total number of lines in your text, including blank and non-blank lines. Ideal for code and data files.",
    icon: "📏",
    category: "text-content",
    toolType: "counter",
    keywords: ["line count", "count lines", "text lines", "newline counter"],
  },
  {
    slug: "sentence-counter",
    name: "Sentence Counter",
    description: "Count the number of sentences in your text. Helpful for readability analysis and meeting editorial content requirements.",
    icon: "💬",
    category: "text-content",
    toolType: "counter",
    keywords: ["sentence count", "count sentences", "text analysis", "content length"],
  },
  {
    slug: "paragraph-counter",
    name: "Paragraph Counter",
    description: "Count paragraphs in your text automatically. Monitor content structure and length for blog posts and articles.",
    icon: "📄",
    category: "text-content",
    toolType: "counter",
    keywords: ["paragraph count", "count paragraphs", "text structure", "content blocks"],
  },
  {
    slug: "random-text-generator",
    name: "Random Text Generator",
    description: "Generate random words, sentences, or paragraphs for testing layouts, prototypes, and design mockups.",
    icon: "🎲",
    category: "text-content",
    toolType: "generator",
    keywords: ["random text", "placeholder text", "dummy text", "test content"],
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate classic Lorem Ipsum placeholder text in paragraphs, sentences, or words for web design and print layouts.",
    icon: "📜",
    category: "text-content",
    toolType: "generator",
    keywords: ["lorem ipsum", "placeholder text", "dummy text", "filler text"],
  },

  // ---------------------------------------------------------------------------
  // Business Tools (16 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "business-name-generator",
    name: "Business Name Generator",
    description: "Generate creative and brandable business name ideas based on your industry and keywords. Find the perfect name for your startup.",
    icon: "💡",
    category: "business-tools",
    toolType: "generator",
    keywords: ["business name", "company name", "brand name", "startup name"],
  },
  {
    slug: "business-slogan-generator",
    name: "Business Slogan Generator",
    description: "Create catchy slogans and taglines for your business. Generate memorable phrases that capture your brand identity.",
    icon: "📢",
    category: "business-tools",
    toolType: "generator",
    keywords: ["slogan generator", "tagline", "brand slogan", "business tagline"],
  },
  {
    slug: "company-description-generator",
    name: "Company Description Generator",
    description: "Write professional company descriptions for your website, Google Business Profile, and social media bios.",
    icon: "🏢",
    category: "business-tools",
    toolType: "generator",
    keywords: ["company description", "about us", "business description", "company bio"],
  },
  {
    slug: "business-bio-generator",
    name: "Business Bio Generator",
    description: "Create compelling professional bios for founders, team members, and business profiles across social platforms.",
    icon: "👤",
    category: "business-tools",
    toolType: "generator",
    keywords: ["business bio", "professional bio", "founder bio", "team bio"],
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional invoices with your business details, line items, taxes, and totals. Download as a printable document.",
    icon: "🧾",
    category: "business-tools",
    toolType: "generator",
    keywords: ["invoice generator", "create invoice", "billing", "free invoice"],
  },
  {
    slug: "quote-generator",
    name: "Quote Generator",
    description: "Generate professional service quotes and estimates for clients. Include itemized pricing, terms, and validity dates.",
    icon: "📑",
    category: "business-tools",
    toolType: "generator",
    keywords: ["quote generator", "estimate", "price quote", "service quote"],
  },
  {
    slug: "receipt-generator",
    name: "Receipt Generator",
    description: "Create printable receipts for transactions with itemized details, payment method, and business information.",
    icon: "🧾",
    category: "business-tools",
    toolType: "generator",
    keywords: ["receipt generator", "payment receipt", "transaction receipt", "sales receipt"],
  },
  {
    slug: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate a comprehensive privacy policy for your website or app. Cover data collection, cookies, and user rights.",
    icon: "🔒",
    category: "business-tools",
    toolType: "generator",
    keywords: ["privacy policy", "data privacy", "gdpr policy", "cookie policy"],
  },
  {
    slug: "terms-conditions-generator",
    name: "Terms & Conditions Generator",
    description: "Create terms and conditions for your website or service. Protect your business with clear legal terms.",
    icon: "📜",
    category: "business-tools",
    toolType: "generator",
    keywords: ["terms conditions", "terms of service", "user agreement", "legal terms"],
  },
  {
    slug: "disclaimer-generator",
    name: "Disclaimer Generator",
    description: "Generate professional disclaimers for your website, blog, or affiliate content. Limit legal liability with proper disclosures.",
    icon: "⚠️",
    category: "business-tools",
    toolType: "generator",
    keywords: ["disclaimer", "legal disclaimer", "website disclaimer", "liability notice"],
  },
  {
    slug: "refund-policy-generator",
    name: "Refund Policy Generator",
    description: "Create a clear refund and cancellation policy for your business. Set expectations for returns and money-back guarantees.",
    icon: "💰",
    category: "business-tools",
    toolType: "generator",
    keywords: ["refund policy", "return policy", "money back", "cancellation policy"],
  },
  {
    slug: "shipping-policy-generator",
    name: "Shipping Policy Generator",
    description: "Generate a detailed shipping policy covering delivery times, costs, tracking, and international shipping guidelines.",
    icon: "📦",
    category: "business-tools",
    toolType: "generator",
    keywords: ["shipping policy", "delivery policy", "shipping terms", "fulfillment"],
  },
  {
    slug: "return-policy-generator",
    name: "Return Policy Generator",
    description: "Create a customer-friendly return policy with clear instructions for product returns, exchanges, and refund timelines.",
    icon: "↩️",
    category: "business-tools",
    toolType: "generator",
    keywords: ["return policy", "exchange policy", "product returns", "return instructions"],
  },
  {
    slug: "cookie-policy-generator",
    name: "Cookie Policy Generator",
    description: "Generate a GDPR-compliant cookie policy explaining what cookies your website uses and how visitors can manage them.",
    icon: "🍪",
    category: "business-tools",
    toolType: "generator",
    keywords: ["cookie policy", "gdpr cookies", "cookie consent", "cookie notice"],
  },
  {
    slug: "business-hours-generator",
    name: "Business Hours Generator",
    description: "Create formatted business hours for your website, Google Business Profile, and social media pages.",
    icon: "🕐",
    category: "business-tools",
    toolType: "generator",
    keywords: ["business hours", "opening hours", "store hours", "schedule"],
  },
  {
    slug: "email-signature-generator",
    name: "Email Signature Generator",
    description: "Design professional HTML email signatures with your name, title, contact info, and social media links.",
    icon: "✉️",
    category: "business-tools",
    toolType: "generator",
    keywords: ["email signature", "html signature", "professional signature", "mail signature"],
  },

  // ---------------------------------------------------------------------------
  // Link Generators (10 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "google-review-qr-generator",
    name: "Google Review QR Generator",
    description: "Create a QR code that links directly to your Google Business review page. Print it on receipts, cards, or signage.",
    icon: "📱",
    category: "link-generators",
    toolType: "generator",
    keywords: ["google review qr", "review qr code", "google rating", "review link"],
  },
  {
    slug: "google-maps-embed-generator",
    name: "Google Maps Embed Generator",
    description: "Generate an embeddable Google Maps iframe for your website. Show your business location with customizable zoom and map type.",
    icon: "🗺️",
    category: "link-generators",
    toolType: "generator",
    keywords: ["google maps embed", "map iframe", "embed map", "location map"],
  },
  {
    slug: "utm-url-builder",
    name: "UTM URL Builder",
    description: "Build UTM-tagged URLs to track marketing campaigns in Google Analytics. Add source, medium, campaign, and content parameters.",
    icon: "📊",
    category: "link-generators",
    toolType: "generator",
    keywords: ["utm builder", "campaign url", "utm parameters", "google analytics"],
  },
  {
    slug: "whatsapp-link-generator",
    name: "WhatsApp Link Generator",
    description: "Create click-to-chat WhatsApp links with a pre-filled message. Add them to your website, email, or social media.",
    icon: "💬",
    category: "link-generators",
    toolType: "generator",
    keywords: ["whatsapp link", "wa.me link", "click to chat", "whatsapp url"],
  },
  {
    slug: "click-to-call-generator",
    name: "Click-to-Call Link Generator",
    description: "Generate tel: links that let mobile visitors call your business with one tap. Get the HTML code ready to paste.",
    icon: "📞",
    category: "link-generators",
    toolType: "generator",
    keywords: ["click to call", "tel link", "phone link", "call button"],
  },
  {
    slug: "mailto-link-generator",
    name: "Mailto Link Generator",
    description: "Create mailto: links with pre-filled subject, body, CC, and BCC fields. Add email contact links to your website instantly.",
    icon: "📧",
    category: "link-generators",
    toolType: "generator",
    keywords: ["mailto link", "email link", "contact link", "email button"],
  },
  {
    slug: "nap-formatter",
    name: "NAP Formatter",
    description: "Format your business Name, Address, and Phone number consistently for local SEO citations across directories and listings.",
    icon: "📍",
    category: "link-generators",
    toolType: "generator",
    keywords: ["nap format", "business citation", "local seo", "name address phone"],
  },
  {
    slug: "google-maps-direction-generator",
    name: "Google Maps Direction Generator",
    description: "Create a direct link to Google Maps directions to your business. Share with customers via text, email, or your website.",
    icon: "🧭",
    category: "link-generators",
    toolType: "generator",
    keywords: ["google maps directions", "direction link", "navigation link", "get directions"],
  },
  {
    slug: "review-link-generator",
    name: "Review Link Generator",
    description: "Generate direct review links for Google, Yelp, Facebook, and other platforms. Make it easy for customers to leave reviews.",
    icon: "⭐",
    category: "link-generators",
    toolType: "generator",
    keywords: ["review link", "google review link", "yelp review", "review url"],
  },
  {
    slug: "business-card-qr-generator",
    name: "Business Card QR Generator",
    description: "Create a QR code containing your business contact details in vCard format. Scan to save your info to any phone.",
    icon: "💳",
    category: "link-generators",
    toolType: "generator",
    keywords: ["business card qr", "vcard qr", "contact qr", "digital business card"],
  },

  // ---------------------------------------------------------------------------
  // Dev Utilities (19 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "html-minifier",
    name: "HTML Minifier",
    description: "Minify HTML code by removing whitespace, comments, and unnecessary attributes to reduce file size and improve load speed.",
    icon: "📄",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["html minify", "compress html", "minify code", "reduce html"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    description: "Compress CSS code by stripping comments, whitespace, and shortening property values for faster page rendering.",
    icon: "🎨",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["css minify", "compress css", "minify stylesheet", "reduce css"],
  },
  {
    slug: "javascript-minifier",
    name: "JavaScript Minifier",
    description: "Minify JavaScript code by removing whitespace, comments, and shortening variable names to reduce bundle size.",
    icon: "⚡",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["js minify", "compress javascript", "minify js", "reduce javascript"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with proper indentation. Quickly spot errors in your JSON structure.",
    icon: "📋",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["json formatter", "json beautify", "json validator", "format json"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for any URL, text, or data. Download as PNG or SVG for print and digital use.",
    icon: "📱",
    category: "dev-utilities",
    toolType: "generator",
    keywords: ["qr code", "qr generator", "create qr", "scan code"],
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in Code128, EAN-13, UPC-A, and other formats for products, inventory, and shipping labels.",
    icon: "📊",
    category: "dev-utilities",
    toolType: "generator",
    keywords: ["barcode", "barcode generator", "ean13", "upc code"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with customizable length and character types. Create secure passwords instantly.",
    icon: "🔐",
    category: "dev-utilities",
    toolType: "generator",
    keywords: ["password generator", "random password", "secure password", "strong password"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate universally unique identifiers (UUID v4) for databases, APIs, and distributed systems. Create one or many at once.",
    icon: "🆔",
    category: "dev-utilities",
    toolType: "generator",
    keywords: ["uuid generator", "guid", "unique id", "random uuid"],
  },
  {
    slug: "md5-generator",
    name: "MD5 Hash Generator",
    description: "Generate MD5 hash checksums from any text input. Useful for data integrity checks and legacy system compatibility.",
    icon: "🔒",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["md5 hash", "md5 generator", "checksum", "hash function"],
  },
  {
    slug: "sha256-generator",
    name: "SHA-256 Hash Generator",
    description: "Generate SHA-256 cryptographic hashes from text input. Widely used for data integrity verification and security.",
    icon: "🛡️",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["sha256 hash", "sha generator", "crypto hash", "hash function"],
  },
  {
    slug: "base64-encode",
    name: "Base64 Encoder",
    description: "Encode text or data to Base64 format for safe transmission in URLs, emails, and API payloads.",
    icon: "🔑",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["base64 encode", "encode text", "data encoding", "base64"],
  },
  {
    slug: "base64-decode",
    name: "Base64 Decoder",
    description: "Decode Base64-encoded strings back to readable text. Inspect encoded data from APIs, cookies, and tokens.",
    icon: "🔓",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["base64 decode", "decode text", "data decoding", "base64"],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between human-readable dates and Unix timestamps. Support for multiple date formats and time zones.",
    icon: "🕰️",
    category: "dev-utilities",
    toolType: "converter",
    keywords: ["timestamp converter", "date converter", "epoch time", "unix time"],
  },
  {
    slug: "unix-time-converter",
    name: "Unix Time Converter",
    description: "Convert Unix epoch timestamps to human-readable dates and vice versa. Supports seconds and milliseconds precision.",
    icon: "⏰",
    category: "dev-utilities",
    toolType: "converter",
    keywords: ["unix time", "epoch converter", "timestamp", "date conversion"],
  },
  {
    slug: "hashtag-generator",
    name: "Hashtag Generator",
    description: "Transform keywords and phrases into formatted hashtags for Instagram, Twitter, TikTok, and LinkedIn posts.",
    icon: "#️⃣",
    category: "dev-utilities",
    toolType: "text-transform",
    keywords: ["hashtag generator", "social hashtags", "instagram tags", "twitter hashtags"],
  },
  {
    slug: "emoji-picker",
    name: "Emoji Picker",
    description: "Browse and copy emojis organized by category. Search by name or keyword and copy to clipboard with one click.",
    icon: "😀",
    category: "dev-utilities",
    toolType: "generator",
    keywords: ["emoji picker", "emoji search", "copy emoji", "emoji keyboard"],
  },
  {
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Design beautiful linear and radial CSS gradients with a visual editor. Copy the CSS code ready for your stylesheet.",
    icon: "🌈",
    category: "dev-utilities",
    toolType: "generator",
    keywords: ["css gradient", "gradient generator", "background gradient", "color gradient"],
  },
  {
    slug: "hex-to-rgb",
    name: "HEX to RGB Converter",
    description: "Convert hexadecimal color codes to RGB values. Preview the color and get CSS-ready rgb() output.",
    icon: "🎨",
    category: "dev-utilities",
    toolType: "converter",
    keywords: ["hex to rgb", "color converter", "hex color", "rgb value"],
  },
  {
    slug: "rgb-to-hex",
    name: "RGB to HEX Converter",
    description: "Convert RGB color values to hexadecimal color codes. Preview the color and copy the hex code for your designs.",
    icon: "🎨",
    category: "dev-utilities",
    toolType: "converter",
    keywords: ["rgb to hex", "color converter", "rgb color", "hex value"],
  },

  // ---------------------------------------------------------------------------
  // Image Tools (10 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images in your browser without losing visible quality. Reduce file size for faster websites.",
    icon: "📉",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["image compression", "compress image", "reduce size", "optimize image"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to exact pixel dimensions or by percentage. Maintain aspect ratio or set custom width and height.",
    icon: "📐",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["resize image", "image dimensions", "scale image", "image size"],
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to custom dimensions or preset aspect ratios like 1:1, 16:9, and 4:3. All processing happens in your browser.",
    icon: "✂️",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["crop image", "image crop", "trim image", "cut image"],
  },
  {
    slug: "jpg-to-webp",
    name: "JPG to WebP Converter",
    description: "Convert JPEG images to WebP format for smaller file sizes and faster web performance. Process multiple files at once.",
    icon: "🔄",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["jpg to webp", "jpeg converter", "webp conversion", "image format"],
  },
  {
    slug: "png-to-webp",
    name: "PNG to WebP Converter",
    description: "Convert PNG images to WebP format to dramatically reduce file size while preserving transparency.",
    icon: "🔄",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["png to webp", "png converter", "webp conversion", "image format"],
  },
  {
    slug: "webp-to-png",
    name: "WebP to PNG Converter",
    description: "Convert WebP images back to PNG format for maximum compatibility with older browsers and design software.",
    icon: "🔄",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["webp to png", "webp converter", "png conversion", "image format"],
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG Converter",
    description: "Convert WebP images to JPEG format with adjustable quality. Perfect for sharing WebP images with apps that don't support the format.",
    icon: "🔄",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["webp to jpg", "webp converter", "jpeg conversion", "image format"],
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG Converter",
    description: "Convert JPEG images to PNG format with transparency support. Ideal for logos, graphics, and images needing lossless quality.",
    icon: "🔄",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["jpg to png", "jpeg converter", "png conversion", "image format"],
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG Converter",
    description: "Convert PNG images to JPEG format with adjustable quality. Reduce file size for photos and images that don't need transparency.",
    icon: "🔄",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["png to jpg", "png converter", "jpeg conversion", "image format"],
  },
  {
    slug: "image-rotator",
    name: "Image Rotator",
    description: "Rotate images by 90, 180, or 270 degrees or set a custom angle. Fix orientation issues directly in your browser.",
    icon: "🔃",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["rotate image", "image rotation", "turn image", "fix orientation"],
  },
  {
    slug: "image-flip",
    name: "Image Flipper",
    description: "Flip images horizontally or vertically with one click. Create mirror effects or correct reversed photos instantly.",
    icon: "↔️",
    category: "image-tools",
    toolType: "image-processor",
    keywords: ["flip image", "mirror image", "horizontal flip", "vertical flip"],
  },

  // ---------------------------------------------------------------------------
  // Calculators (4 tools)
  // ---------------------------------------------------------------------------
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, percentage change, and what percent one number is of another. Solve any percentage problem instantly.",
    icon: "%",
    category: "calculators",
    toolType: "calculator",
    keywords: ["percentage calculator", "percent", "percentage change", "calculate percent"],
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    description: "Calculate GST-inclusive and GST-exclusive prices for any tax rate. Support for standard GST slabs and custom rates.",
    icon: "🧾",
    category: "calculators",
    toolType: "calculator",
    keywords: ["gst calculator", "tax calculator", "goods services tax", "vat calculator"],
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    description: "Calculate gross profit margin, net profit margin, and markup percentage from cost and revenue figures.",
    icon: "📈",
    category: "calculators",
    toolType: "calculator",
    keywords: ["profit margin", "markup calculator", "gross margin", "net margin"],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate the final price after applying a percentage or fixed discount. See how much you save on any purchase.",
    icon: "🏷️",
    category: "calculators",
    toolType: "calculator",
    keywords: ["discount calculator", "sale price", "percent off", "price discount"],
  },
];

export function getUtilityTool(slug: string): UtilityToolDefinition | undefined {
  return UTILITY_TOOLS.find((t) => t.slug === slug);
}

export function getUtilityToolsByCategory(category: UtilityToolCategory): UtilityToolDefinition[] {
  return UTILITY_TOOLS.filter((t) => t.category === category);
}

export function getAllUtilityTools(): UtilityToolDefinition[] {
  return UTILITY_TOOLS;
}
